server {
  # O Nginx vai escutar na porta 80.
  listen 80;

  # Define a raiz onde os arquivos do site estão localizados.
  root /usr/share/nginx/html;

  # Adiciona o index.html como a página padrão.
  index index.html;

  # Configuração para lidar com o roteamento do React.
  # Se uma requisição para um arquivo ou diretório não for encontrada,
  # ele redireciona para o index.html. Isso permite que o React Router
  # controle a navegação.
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Opcional: Melhora o cache para arquivos estáticos.
  location ~* \.(?:css|js|jpg|jpeg|gif|png|svg|ico|webp)$ {
    expires 1y;
    add_header Cache-Control "public";
  }
}